# Generated by Django 2.0.4 on 2018-05-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captain_firstname', models.CharField(max_length=64)),
                ('captain_surname', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'Crews',
            },
        ),
        migrations.AlterUniqueTogether(
            name='crew',
            unique_together={('captain_firstname', 'captain_surname')},
        ),
        migrations.AddField(
            model_name='flight',
            name='crew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Crew'),
        ),
    ]
