# Generated by Django 2.0.4 on 2018-05-28 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0003_flight_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crew',
            old_name='captain_surname',
            new_name='captain_lastname',
        ),
        migrations.AlterField(
            model_name='flight',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.Crew'),
        ),
        migrations.AlterUniqueTogether(
            name='crew',
            unique_together={('captain_firstname', 'captain_lastname')},
        ),
    ]
